version: 0.1

phases:
  install:
    runtime-version:
      nodejs: 10
  pre_build:
    commands:
      - echo installing dependencies...
      - npm i -g @angular/cli
      - npm install
  build:
    commands:
      # - echo testing...
      # - echo building...
      - ng build --prod
  post_build:
    commands:
      - mv appspec.yml ./dist/my-dream-app
      - mv scripts ./dist/my-dream-app
artifacts:
  files:
    - "**/*"
    - dist/**/*
  discard-paths: no
  base-directory: dist/my-dream-app

